services:
  - type: web
    name: virtual-tour-generator
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python src/main.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 5000

