name: Render Real Estate Video

on:
  workflow_dispatch:
    inputs:
      images:
        description: 'JSON array of image URLs'
        required: true
        type: string
      propertyDetails:
        description: 'JSON object with property details'
        required: true
        type: string
      settings:
        description: 'JSON object with render settings'
        required: false
        type: string
        default: '{"durationPerImage":8,"effectSpeed":"medium","transitionDuration":1.5}'
      watermark:
        description: 'JSON object with watermark configuration'
        required: false
        type: string
        default: ''
      jobId:
        description: 'Unique job identifier'
        required: true
        type: string

jobs:
  render-video:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: 'remotion-tours/package-lock.json'
    
    - name: Install dependencies
      working-directory: ./remotion-tours
      run: |
        echo "Installing dependencies..."
        echo "Node version: $(node --version)"
        echo "NPM version: $(npm --version)"
        
        # Clear npm cache to avoid issues
        echo "Clearing npm cache..."
        npm cache clean --force || echo "Cache clean failed, continuing..."
        
        # Check if package-lock.json exists
        if [ ! -f "package-lock.json" ]; then
          echo "ERROR: package-lock.json not found!"
          echo "Running npm install instead of npm ci..."
          npm install --legacy-peer-deps
        else
          echo "package-lock.json found, running npm ci..."
          npm ci || {
            echo "npm ci failed, trying npm install..."
            rm -rf node_modules package-lock.json
            npm install --legacy-peer-deps
          }
        fi
        
        # Ensure Remotion CLI is available
        echo "Ensuring Remotion CLI is available..."
        if ! npx remotion --version 2>/dev/null; then
          echo "Remotion CLI not found, installing..."
          npm install @remotion/cli@^4.0.331
        fi
        
        # Verify all dependencies
        echo "Verifying installations..."
        npx remotion --version || echo "ERROR: Remotion CLI still not accessible!"
        
        # List installed packages for debugging
        echo "Key packages installed:"
        npm list remotion @remotion/cli react react-dom --depth=0 || true
    
    - name: Parse inputs
      id: parse
      run: |
        echo "Parsing inputs..."
        
        # Log raw images input
        echo "Raw images input:"
        echo '${{ inputs.images }}'
        
        # Save inputs to files using cat with heredoc to avoid shell interpretation
        cat > /tmp/images.json << 'EOF'
        ${{ inputs.images }}
        EOF
        
        cat > /tmp/propertyDetails.json << 'EOF'
        ${{ inputs.propertyDetails }}
        EOF
        
        cat > /tmp/settings.json << 'EOF'
        ${{ inputs.settings }}
        EOF
        
        # Log parsed image count
        echo "Parsed image count:"
        node -e "const imgs = JSON.parse(require('fs').readFileSync('/tmp/images.json', 'utf8')); console.log('Total images:', imgs.length); imgs.forEach((img, i) => console.log(\`  Image \${i+1}: \${img}\`));"
        
        echo "Inputs saved to temporary files"
    
    - name: Test Image Accessibility
      run: |
        echo "Testing if GitHub Actions can access storage images..."
        
        # Parse the first image URL for testing
        FIRST_IMAGE=$(node -e "
          const images = JSON.parse(require('fs').readFileSync('/tmp/images.json', 'utf8'));
          if (images.length > 0) {
            console.log(images[0]);
          }
        ")
        
        if [ -n "$FIRST_IMAGE" ]; then
          echo "Testing access to: $FIRST_IMAGE"
          
          # Test with curl
          echo "Testing with curl..."
          curl -I "$FIRST_IMAGE" 2>/dev/null | head -n 5 || echo "curl failed"
          
          # Test actual download
          echo "Testing actual download..."
          curl -o test_image.jpg "$FIRST_IMAGE" --max-time 30 2>&1 || echo "Download failed"
          
          if [ -f "test_image.jpg" ]; then
            FILE_SIZE=$(stat -c%s "test_image.jpg" 2>/dev/null || stat -f%z "test_image.jpg" 2>/dev/null || echo "0")
            echo "Downloaded image size: $FILE_SIZE bytes"
            if [ "$FILE_SIZE" -gt "0" ]; then
              echo "✓ Image is accessible from GitHub Actions"
            else
              echo "✗ Image downloaded but is empty"
            fi
            rm -f test_image.jpg
          else
            echo "✗ Failed to download image from storage"
            echo "This might be why Remotion is failing!"
          fi
        else
          echo "No images provided to test"
        fi
    
    - name: Render video with Remotion
      working-directory: ./remotion-tours
      env:
        REMOTION_IMAGES: ${{ inputs.images }}
        REMOTION_PROPERTY_DETAILS: ${{ inputs.propertyDetails }}
        REMOTION_SETTINGS: ${{ inputs.settings }}
        JOB_ID: ${{ inputs.jobId }}
      run: |
        echo "Starting FULL Remotion render..."
        
        # Debug: Check current directory and files
        echo "Current directory: $(pwd)"
        echo "Directory contents:"
        ls -la
        
        # Verify src files exist
        echo "Checking src directory:"
        ls -la src/ || echo "ERROR: src directory not found!"
        
        # Log the number of images received
        echo "Images input: ${{ inputs.images }}"
        echo "Number of images: $(node -e "console.log(JSON.parse(process.env.REMOTION_IMAGES).length)" 2>/dev/null || echo "ERROR parsing images")"
        
        # Log each image URL
        node -e "
          try {
            const images = JSON.parse(process.env.REMOTION_IMAGES);
            console.log('Image URLs received:');
            images.forEach((url, index) => {
              console.log(\`  Image \${index + 1}: \${url}\`);
            });
          } catch (e) {
            console.error('ERROR parsing images:', e.message);
            process.exit(1);
          }
        " || exit 1
        
        # Create output directory
        mkdir -p out
        
        # Generate props JSON file for debugging
        node -e "
          try {
            const images = JSON.parse(process.env.REMOTION_IMAGES);
            const propertyDetails = JSON.parse(process.env.REMOTION_PROPERTY_DETAILS);
            const settings = JSON.parse(process.env.REMOTION_SETTINGS);
            const props = { images, propertyDetails, settings };
            
            require('fs').writeFileSync('props.json', JSON.stringify(props, null, 2));
            console.log('Props saved to props.json');
          } catch (e) {
            console.error('ERROR generating props:', e.message);
            process.exit(1);
          }
        " || exit 1
        
        echo "Props JSON:"
        cat props.json || echo "ERROR: props.json not created"
        
        # Show the exact command that will be run
        echo "=== EXACT REMOTION COMMAND ==="
        echo "npx remotion render RealEstateTour out/${{ inputs.jobId }}.mp4 --props=props.json"
        echo "=== END COMMAND ==="
        
        # Check if any image URLs contain problematic characters
        node -e "
          const images = JSON.parse(process.env.REMOTION_IMAGES);
          images.forEach((url, i) => {
            if (url.includes('\"') || url.includes(\"'\")) {
              console.error(\`WARNING: Image \${i+1} contains quotes which may break the command\`);
            }
          });
        "
        
        # Render the video with error handling
        echo "Executing Remotion render command..."
        echo "Memory before render: $(free -h 2>/dev/null | grep Mem || echo 'N/A')"
        
        # Try with reduced concurrency to avoid memory issues
        npx remotion render RealEstateTour out/${{ inputs.jobId }}.mp4 \
          --props=props.json \
          --concurrency=4 \
          --timeout=300000 \
          2>&1 | tee render.log || {
            echo "ERROR: Remotion render failed!"
            echo "Full render log:"
            cat render.log
            
            # Check for specific error patterns
            if grep -q "Failed to fetch" render.log; then
              echo "ERROR: Remotion could not fetch images from storage"
              echo "This is likely a network/access issue"
            fi
            
            if grep -q "out of memory" render.log; then
              echo "ERROR: Remotion ran out of memory"
              echo "Reducing image count or resolution may help"
            fi
            
            if grep -q "durationInFrames" render.log; then
              echo "ERROR: Duration calculation issue"
              echo "Check the composition's calculateMetadata function"
            fi
            
            exit 1
          }
        
        echo "Memory after render: $(free -h 2>/dev/null | grep Mem || echo 'N/A')"
        
        # Check if video was created
        if [ -f "out/${{ inputs.jobId }}.mp4" ]; then
          echo "Video rendered successfully!"
          VIDEO_SIZE=$(stat -c%s "out/${{ inputs.jobId }}.mp4" 2>/dev/null || stat -f%z "out/${{ inputs.jobId }}.mp4" 2>/dev/null || echo "0")
          echo "Video size: ${VIDEO_SIZE} bytes"
          echo "VIDEO_PATH=out/${{ inputs.jobId }}.mp4" >> $GITHUB_ENV
        else
          echo "ERROR: Video file not found after render!"
          echo "Directory contents:"
          ls -la out/
          exit 1
        fi
    
    - name: Upload to Bunny.net Storage
      working-directory: ./remotion-tours
      env:
        BUNNY_STORAGE_ZONE_NAME: ${{ secrets.BUNNY_STORAGE_ZONE_NAME }}
        BUNNY_ACCESS_KEY: ${{ secrets.BUNNY_ACCESS_KEY }}
        BUNNY_PULL_ZONE_URL: ${{ secrets.BUNNY_PULL_ZONE_URL }}
        BUNNY_REGION: ${{ secrets.BUNNY_REGION }}
        VIDEO_PATH: ${{ env.VIDEO_PATH }}
        JOB_ID: ${{ inputs.jobId }}
      run: |
        echo "Uploading video to Bunny.net Storage..."
        echo "Current directory: $(pwd)"
        echo "Video path: ${VIDEO_PATH}"
        
        # Verify environment variables
        if [ -z "${BUNNY_STORAGE_ZONE_NAME}" ]; then
          echo "ERROR: BUNNY_STORAGE_ZONE_NAME is not set!"
          echo "Please add BUNNY_STORAGE_ZONE_NAME to GitHub Secrets"
          exit 1
        fi
        
        if [ -z "${BUNNY_ACCESS_KEY}" ]; then
          echo "ERROR: BUNNY_ACCESS_KEY is not set!"
          echo "Please add BUNNY_ACCESS_KEY to GitHub Secrets"
          exit 1
        fi
        
        if [ -z "${BUNNY_PULL_ZONE_URL}" ]; then
          echo "ERROR: BUNNY_PULL_ZONE_URL is not set!"
          echo "Please add BUNNY_PULL_ZONE_URL to GitHub Secrets"
          exit 1
        fi
        
        echo "Bunny.net credentials are configured (values hidden for security)"
        
        # Verify video file exists and has content
        if [ ! -f "${VIDEO_PATH}" ]; then
          echo "ERROR: Video file not found at ${VIDEO_PATH}"
          echo "Directory contents:"
          ls -la out/
          exit 1
        fi
        
        VIDEO_SIZE=$(stat -c%s "${VIDEO_PATH}" 2>/dev/null || stat -f%z "${VIDEO_PATH}" 2>/dev/null || echo "0")
        echo "Video file size: ${VIDEO_SIZE} bytes"
        VIDEO_SIZE_MB=$((VIDEO_SIZE / 1048576))
        echo "Video file size: ${VIDEO_SIZE_MB} MB"
        
        if [ "${VIDEO_SIZE}" -eq "0" ]; then
          echo "ERROR: Video file is empty"
          exit 1
        fi
        
        # Set up Bunny.net storage URL
        REGION="${BUNNY_REGION:-ny}"
        if [ "${REGION}" = "default" ] || [ -z "${REGION}" ]; then
          STORAGE_URL="https://storage.bunnycdn.com/${BUNNY_STORAGE_ZONE_NAME}"
        else
          STORAGE_URL="https://${REGION}.storage.bunnycdn.com/${BUNNY_STORAGE_ZONE_NAME}"
        fi
        
        # Create the upload path
        UPLOAD_PATH="tours/videos/${JOB_ID}.mp4"
        FULL_UPLOAD_URL="${STORAGE_URL}/${UPLOAD_PATH}"
        
        echo "Storage URL: ${STORAGE_URL}"
        echo "Upload Path: ${UPLOAD_PATH}"
        echo "Full Upload URL: ${FULL_UPLOAD_URL}"
        
        # Upload using cURL
        echo "Uploading video to Bunny.net..."
        
        HTTP_RESPONSE=$(curl -w "\nHTTP_STATUS:%{http_code}" \
          -X PUT \
          -H "AccessKey: ${BUNNY_ACCESS_KEY}" \
          -H "Content-Type: application/octet-stream" \
          -H "accept: application/json" \
          -T "${VIDEO_PATH}" \
          "${FULL_UPLOAD_URL}" 2>/dev/null)
        
        # Extract HTTP status code
        HTTP_STATUS=$(echo "${HTTP_RESPONSE}" | grep "HTTP_STATUS:" | cut -d: -f2)
        HTTP_BODY=$(echo "${HTTP_RESPONSE}" | sed '/HTTP_STATUS:/d')
        
        echo "HTTP Status: ${HTTP_STATUS}"
        echo "Response: ${HTTP_BODY}"
        
        # Check if upload was successful
        if [ "${HTTP_STATUS}" = "200" ] || [ "${HTTP_STATUS}" = "201" ]; then
          echo "✓ Successfully uploaded video to Bunny.net!"
          
          # Construct the CDN URL
          VIDEO_URL="${BUNNY_PULL_ZONE_URL}/tours/videos/${JOB_ID}.mp4"
          echo "VIDEO_URL=${VIDEO_URL}"
          
          # Write to GITHUB_ENV for other steps to use
          echo "VIDEO_URL=${VIDEO_URL}" >> $GITHUB_ENV
          
          echo "Video is available at: ${VIDEO_URL}"
          
          # Verify the video is accessible
          echo "Verifying video accessibility..."
          VERIFY_STATUS=$(curl -s -o /dev/null -w "%{http_code}" "${VIDEO_URL}")
          if [ "${VERIFY_STATUS}" = "200" ]; then
            echo "✓ Video is accessible at CDN URL"
          else
            echo "⚠ Warning: Video uploaded but not yet accessible at CDN (status: ${VERIFY_STATUS})"
            echo "This may be due to CDN propagation delay"
          fi
        else
          echo "✗ Failed to upload video to Bunny.net"
          echo "HTTP Status: ${HTTP_STATUS}"
          echo "Response: ${HTTP_BODY}"
          exit 1
        fi
    
    - name: Create result artifact
      run: |
        # Create a result file with the video URL and metadata
        # Ensure VIDEO_URL has a default value if empty
        if [ -z "${VIDEO_URL}" ]; then
          echo "WARNING: VIDEO_URL is empty, using placeholder"
          VIDEO_URL="error:no-video-url"
        fi
        
        # Calculate duration safely
        DURATION=$(node -e "
          try {
            const s = JSON.parse('${{ inputs.settings }}');
            const i = JSON.parse('${{ inputs.images }}');
            console.log(s.durationPerImage * i.length);
          } catch (e) {
            console.log(0);
          }
        ")
        
        # Create JSON with proper escaping
        cat > result.json << EOF
        {
          "success": true,
          "jobId": "${{ inputs.jobId }}",
          "videoUrl": "${VIDEO_URL}",
          "duration": ${DURATION:-0},
          "renderTime": "${{ steps.render.outputs.duration }}",
          "timestamp": "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
        }
        EOF
        
        # Validate JSON before proceeding
        if ! jq . result.json > /dev/null 2>&1; then
          echo "ERROR: Invalid JSON generated, creating fallback"
          cat > result.json << EOF
        {
          "success": false,
          "jobId": "${{ inputs.jobId }}",
          "videoUrl": "error:invalid-json",
          "duration": 0,
          "renderTime": "unknown",
          "timestamp": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
          "error": "Failed to generate valid result JSON"
        }
        EOF
        fi
        
        echo "Result JSON:"
        cat result.json
    
    - name: Upload result as artifact
      uses: actions/upload-artifact@v4
      with:
        name: render-result-${{ inputs.jobId }}
        path: result.json
        retention-days: 7
    
    - name: Upload video as artifact (backup)
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: video-${{ inputs.jobId }}
        path: remotion-tours/out/${{ inputs.jobId }}.mp4
        retention-days: 7
      continue-on-error: true
    
    - name: Notify completion (webhook)
      if: always()
      run: |
        # If you have a webhook URL, notify the Railway app
        # For now, the app will poll for the artifact
        echo "Render job completed with status: ${{ job.status }}"